package com.example.jingangfarmmanagement.repository.entity.Enum;

public enum ELogType {
    DEFAULT,IMPORT,CREATE_PET,UPDATE_PET,DELETE_PET,DEATH,CREATE_TREATMENT_CARD,UPDATE_TREATMENT_CARD,CREATE_MATERIAL,CREATE_USER,UPDATE_USER,CREATE_UILNESS,UPDATE_UILNESS
}
